[ADD] [MOBILE] Merge of all the features from the sprint that where i…
GuardosEpitech/Guardos-mobile pull request #9
Opened 2024-01-29 15:46 UTC by RenanDbs

…n 'dev' repo

### 🛠 Changes being made

Here give examples of the changes you've made in this pull request. Include an itemized list if you can. It'll help the reviewer

### ✨ What's the context?

What's the context for the changes? Are there any

### 🧠 Rationale behind the change

Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🧪 Test plan

How do you know the changes are safe to ship to production?

### 📸 Screenshots (optional)

If you made UI changes, what are the before an afters?

### 🏎 PR checklist

1. Read the ticket
- [ ] Read the related ticket on Jira and understand the requirements for this ticket. In case anything is unclear, ask the ticket creator or ticket executor.
2. Matching PR description
- [ ] Check that the PR description on GitHub is aligned with the ticket description on Jira.
3. Review the changes on GitHub
- [ ] is the current version of the destination branch (mostly main) merged into the PR branch?
- [ ] does it fulfill the definition of done for the ticket?
- [ ] were the tests adjusted or extended for the changed behavior?
- [ ] was the documentation adjusted or extended for changed behavior?
- [ ] does it align with the team code guidelines?
- [ ] check readability of code - is it easy to understand what is happening in the code snippets?
- [ ] proper naming
- [ ] is it logical?
- [ ] are there any performance issues?
- [ ] could it be improved / simplified?
4. Execute locally / in testing environment
- [ ] Execute the code locally and check if there are any issues. Test whether the new behavior from the ticket acts as expected. Try to think of edge cases and test them.
5. Run tests
- [ ] Run the tests locally and check that all of them succeed.
6. Linting & Formatting
- [ ] Check that the changes didn’t cause any linting or formatting warnings of errors.
7. Submit Feedback
- [ ] Approve if all of the following points fulfilled:
   - all previous steps did not reveal any issues
   - there are no open comments on the PR

- [ ] otherwise, request changes with specific comments (constructive) on what to change!

2024-01-29 22:23 UTC, MarcPIster requested changes

2024-01-29 22:23 UTC, MarcPIster commented on restoMobile/src/components/RestaurantCard.tsx
> +              ? require('/Users/duboisrenan/Guardos-mobile/restoMobile/src/assets/logo.png')
Dont use complete paths

2024-01-29 22:23 UTC, MarcPIster commented on restoMobile/src/pages/AddRestaurant/AddRestaurant.tsx
> +      const response = await axios.post('http://195.90.210.111:8081/api/restaurants/', restaurantData);
Move this to restoMobile/src/services/restoCalls.ts and use url from .env

2024-01-29 22:23 UTC, MarcPIster commented on restoMobile/src/pages/HomeScreen/HomeScreen.tsx
> +const baseUrl = `http://195.90.210.111:8081/api/restaurants/`;
use .env

2024-01-29 22:23 UTC, MarcPIster commented on restoMobile/src/pages/HomeScreen/HomeScreen.tsx
> +export const getAllResto = async () => {
move to restoMobile/src/services/restoCalls.ts and use user login token

2024-01-29 22:23 UTC, MarcPIster commented on restoMobile/src/pages/MenuPage/MenuPage.tsx
> +        const response = await fetch(`http://195.90.210.111:8081/api/dishes/${restaurantName}`);
use restoMobile/src/services/dishsCalls.ts and use user login token

2024-01-30 03:50 UTC, JosefineM2000 requested changes
Please change the title of this PR according to our commit policy (specifically state the change, in a short way): https://epitech-eip.atlassian.net/wiki/spaces/EIP/pages/5963782/Commit+policy

Also, adjust the description template.

2024-02-15 11:17 UTC, JosefineM2000 requested changes
Could test it locally yet, but here already some comments from reading the code

2024-02-15 11:17 UTC, JosefineM2000 commented on restoMobile/src/pages/AddRestaurant/AddRestaurant.tsx
> +      location: {
what about opening hours as optional input?

2024-02-15 11:17 UTC, JosefineM2000 commented on restoMobile/src/pages/HomeScreen/HomeScreen.tsx
> +  ratingCount?: number;
opening hours are missing again

2024-02-15 11:17 UTC, JosefineM2000 commented on restoMobile/src/pages/HomeScreen/HomeScreen.tsx
> +const deleteRestaurantByName = async (restaurantName: string) => {
Please move this to the resto call service. BE calls should only be started by a service.

2024-02-15 11:17 UTC, JosefineM2000 commented on restoMobile/src/pages/HomeScreen/HomeScreen.tsx
> +export interface IRestaurantFrontEnd {
interfaces should be in the models folder

2024-02-15 11:17 UTC, JosefineM2000 commented on restoMobile/src/pages/MenuPage/MenuPage.tsx
> +interface Dish {
please move this interface to the models folder

2024-02-15 11:17 UTC, JosefineM2000 commented on restoMobile/src/pages/MenuPage/MenuPage.tsx
> +interface DishData {
this looks like its only used in this file, so you DONT have to move it to the models folder.

2024-02-15 11:17 UTC, JosefineM2000 commented on restoMobile/src/pages/MenuPage/MenuPage.tsx
> +  console.log(restaurantName);
do we still need the log or was it just for testing purposes?

2024-02-15 11:17 UTC, JosefineM2000 commented on restoMobile/src/pages/MenuPage/MenuPage.tsx
> +        <Text>Loading...</Text>
Nice!

2024-02-15 11:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/MenuPage/MenuPage.tsx
> +    console.log("item.dishes[0]", item.dishes[0]);
do we still need those logs?

2024-02-15 11:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/MenuPage/MenuPage.tsx
> +  const dishes = [
Mh, why do we have a hardcoded dish?

2024-02-15 11:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/MenuPage/MenuPage.tsx
> +        source={{ uri: '/Users/duboisrenan/Guardos-dev/packages/restoMobile/src/assets/foodbg.png' }}
As Marc already mentioned before, please dont use paths that only work on your device

2024-02-15 11:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/MenuPage/MenuPage.tsx
> +const styles = StyleSheet.create({
Styles should be in an extra file

2024-02-15 11:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
> +export interface IRestaurantFrontEnd {
should also be in models folder.

and please add opening hours to make it complete

2024-02-17 05:24 UTC, JosefineM2000 requested changes
The opening hours are still missing - should be in add resto, and the resto card / resto details (both for resto and visitor version)

2024-02-17 05:24 UTC, JosefineM2000 commented on restoMobile/src/pages/AddRestaurant/AddRestaurant.tsx
> +    if (!restaurantName || phoneNumber || !streetName || !streetNumber || !postalCode || !city || !country || description || website) {
Please remove phoneNumber, description and website from this statement - right now it will cause an error if a value is set :D

2024-02-17 05:24 UTC, JosefineM2000 commented on restoMobile/src/pages/AddRestaurant/AddRestaurant.tsx
> +    if (!restaurantName || phoneNumber || !streetName || !streetNumber || !postalCode || !city || !country || description || website) {
The same checks should be done in the edit resto screen. And why cant we change the picture in the edit screen? Do you know, who was responsible for edit screen?

2024-02-17 05:24 UTC, JosefineM2000 commented on restoMobile/src/pages/AddRestaurant/AddRestaurant.tsx
> +            placeholder="Phone Number *"
Remove star that indicates required field

2024-02-17 05:24 UTC, JosefineM2000 commented on restoMobile/src/pages/AddRestaurant/AddRestaurant.tsx
> +            placeholder="Description *"
Remove star that indicates required field

2024-02-17 05:24 UTC, JosefineM2000 commented on restoMobile/src/pages/AddRestaurant/AddRestaurant.tsx
> +          placeholder="Website *"
Remove star that indicates required field

2024-02-17 05:24 UTC, JosefineM2000 commented on restoMobile/src/pages/MenuPage/MenuPage.tsx
> +                <View style={styles.cardContent}>
Sometimes the content extends the default dimensions of the dish card. Please make it extendable on click, so that all text is visible. Also, maybe its better to place price (and maybe even allergens) above the description, since that is more important information than description. Its fine to crop the description on limited space, but price should always be visible.

2024-02-17 05:24 UTC, JosefineM2000 commented on visitorMobile/src/pages/MenuPage/MenuPage.tsx
> +                <Image source={{ uri: dish.pictures[0] }} style={styles.cardImage} />
Sometimes the content extends the default dimensions of the dish card. Please make it extendable on click, so that all text is visible. Also, maybe its better to place price (and maybe even allergens) above the description, since that is more important information than description. Its fine to crop the description on limited space, but price should always be visible.

2024-02-17 05:24 UTC, JosefineM2000 commented on visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
> +  const navigateToMenu = (restaurantId: number, restaurantName: string) => {
On click, the resto card should be extended. Redirecting to the menu should happen via a menu button. Also the details button is missing. Was there a reason to choose a different approach to the web version?

2024-02-17 05:24 UTC, JosefineM2000 commented on restoMobile/src/pages/HomeScreen/HomeScreen.tsx
> +  const navigateToMenu = (restaurantId: number, restaurantName: string) => {
On click on the resto, the card should be extended. The menu should be accessable by another button next to edit and delete. - similar to the web version. Not redirect to the menu right away. Or was there a reason to choose a different approach?

2024-02-17 05:24 UTC, JosefineM2000 commented on restoMobile/src/pages/HomeScreen/HomeScreen.tsx
> +  const onDelete = async (restaurantName: string) => {
Please add a popup for verifying that the resto should be deleted to avoid actions on accident.

2024-02-17 06:55 UTC, JosefineM2000 approved these changes
Remaining comments will be resolved in new PR.

Additional note: currently two add resto screens exist and the wrong one is used. This also needs to be resolved in the separate PR.

2024-02-17 07:01 UTC, merged