Back log alban nov
GuardosEpitech/Guardos-mobile pull request #98
Opened 2024-11-14 11:27 UTC by Alban-de-tourtier

### 🛠 Changes being made

Here give examples of the changes you've made in this pull request. Include an itemized list if you can. It'll help the reviewer

### ✨ What's the context?

What's the context for the changes? Are there any

### 🧠 Rationale behind the change

Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🧪 Test plan

How do you know the changes are safe to ship to production?

### 📸 Screenshots (optional)

If you made UI changes, what are the before an afters?

### 🏎 PR checklist

1. Read the ticket
- [ ] Read the related ticket on Jira and understand the requirements for this ticket. In case anything is unclear, ask the ticket creator or ticket executor.
2. Matching PR description
- [ ] Check that the PR description on GitHub is aligned with the ticket description on Jira.
3. Review the changes on GitHub
- [ ] is the current version of the destination branch (mostly main) merged into the PR branch?
- [ ] does it fulfill the definition of done for the ticket?
- [ ] were the tests adjusted or extended for the changed behavior?
- [ ] was the documentation adjusted or extended for changed behavior?
- [ ] does it align with the team code guidelines?
- [ ] check readability of code - is it easy to understand what is happening in the code snippets?
- [ ] proper naming
- [ ] is it logical?
- [ ] are there any performance issues?
- [ ] could it be improved / simplified?
4. Execute locally / in testing environment
- [ ] Execute the code locally and check if there are any issues. Test whether the new behavior from the ticket acts as expected. Try to think of edge cases and test them.
5. Run tests
- [ ] Run the tests locally and check that all of them succeed.
6. Linting & Formatting
- [ ] Check that the changes didn’t cause any linting or formatting warnings of errors.
7. Submit Feedback
- [ ] Approve if all of the following points fulfilled:
   - all previous steps did not reveal any issues
   - there are no open comments on the PR

- [ ] otherwise, request changes with specific comments (constructive) on what to change!

2024-11-14 12:17 UTC, JosefineM2000 requested changes

2024-11-14 12:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/RatingPage/Rating.tsx
> +        ]
semicolon missing

2024-11-14 12:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/RatingPage/Rating.tsx
> +                const userToken = await AsyncStorage.getItem('user');
userToken instead of user

2024-11-14 12:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/RatingPage/Rating.tsx
> +            const userToken = await AsyncStorage.getItem('user');
userToken instead of user and null check missing

2024-11-14 12:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/RatingPage/Rating.tsx
> +                placeholder={'Note'}
translate here and in line below

2024-11-14 12:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/RatingPage/Rating.tsx
> +                placeholder={"Your comment"}
translate

2024-11-14 12:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/UserReviewPage/UserReview.tsx
> +                const userToken = await AsyncStorage.getItem('user');
'userToken'

2024-11-14 12:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/UserReviewPage/UserReview.tsx
> +            const userToken = await AsyncStorage.getItem('user');
userToken
null check missing

2024-11-14 12:17 UTC, JosefineM2000 commented on visitorMobile/src/services/ratingCalls.ts
> +    `${API_URL}`;
newline not needed

2024-11-14 12:17 UTC, JosefineM2000 commented on visitorMobile/src/pages/UserReviewPage/UserReview.tsx
Isn't that the same as Rating.tsx?

2024-11-14 12:17 UTC, JosefineM2000 commented on visitorMobile/src/components/RestaurantCard/RestaurantCard.tsx
> +          <TouchableOpacity  style={styles.button} onPress={navigateToReview}>
I cant click on that, it leads me to the menu

2024-11-14 12:41 UTC, Alban-de-tourtier commented on visitorMobile/src/pages/UserReviewPage/UserReview.tsx
no you can delete and you only see your review

2024-11-14 12:53 UTC, Alban-de-tourtier commented on visitorMobile/src/components/RestaurantCard/RestaurantCard.tsx
> +          <TouchableOpacity  style={styles.button} onPress={navigateToReview}>
can I have a screenrecord?

2024-11-16 12:50 UTC, JosefineM2000 commented on visitorMobile/src/pages/RatingPage/Rating.tsx
> +         }
else what?

2024-11-16 13:12 UTC, MarcPIster commented on visitorMobile/src/pages/RatingPage/Rating.tsx
> +         }
fixed

2024-11-16 13:12 UTC, MarcPIster approved these changes

2024-11-16 13:58 UTC, JosefineM2000 approved these changes

2024-11-16 13:58 UTC, merged